[package]
authors = ["Midas Lambrichts <midaslamb@gmail.com>"]
description = "The CV of Midas Lambrichts"
edition = "2018"
name = "curriculum-vitae"
version = "0.1.0"

[dependencies]
chrono = "0.4"
yew = "0.18"
