[tasks.build]
args = ["build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "./static", "--no-typescript"]
command = "wasm-pack"
dependencies = ["format"]

[tasks.format]
args = ["fmt"]
command = "cargo"

[tasks.watch]
run_task = "build"
watch = {watch = ["./src", "./scss"]}

[tasks.serve]
args = ["-i", "./static/", "-p", "8080", "--nocache", "--try-file", "./static/index.html"]
command = "simple-http-server"

[tasks.dev]
run_task = {name = ["serve", "watch"], parallel = true}
